// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Desenvolvimento/todo/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/Desenvolvimento/todo/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('todo', appParameters);
});
require('c:/Desenvolvimento/todo/index.js');